### PR TITLE
Add separator option

### LINKED ISSUE #45: Add separator option
Do you think it would be a good idea to have a _separator_ option? 

It would works as follows:

```javascript
pageTitle({
  suffix: 'The Best Page On The Internet',
  separator: ' - ',
})
```

The page title will be:

- `'The Best Page On The Internet'` for `useTitle(ref(''))`
- `'Photos - The Best Page On The Internet'` for `useTitle(ref('Photos'))`

So it doesn't add the _separator_ if the title is blank. I see this as useful for homepages or for pages that get their title asynchronously.

### PR DESCRIPTION
**Pull request by janosrusiczki**
Fixes #45

### CODE REVIEW

**Comment by vinicius73** [comment]
Thanks a lot @janosrusiczki !
It is excellent.

What do you think about change `glue` to `separator`  ?

**Comment by janosrusiczki** [comment]
@vinicius73 It is renamed and the linter errors are fixed. You can trigger a build.

**Comment by janosrusiczki** [comment]
I made just a tiny documented change when the value is not set: https://github.com/vinicius73/vue-page-title/pull/46/commits/1b8a999e006997ce402d2533753d81c3367ab8e2#diff-9e3c62c92bfd2907afd44329e96b1e6b09591117f984c10aa24a2be7e00f7cd6R23

**Comment by vinicius73** [comment]
thanks a lot @janosrusiczki

**Comment by janosrusiczki** [comment]
Thank *you* for the quick reaction. 👍

**Pull request merged**
